### ISSUE TITLE
⚠️ Page template is saved on SK and can not be overriden per page

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#218]
The page layout is being saved in the SK, we should detach it.

**Comment by JohnPixle** [comment]
![Screenshot 2019-11-09 at 09 25 12](https://user-images.githubusercontent.com/4193672/68525018-0813e580-02d6-11ea-976b-63dbc77607b5.png)

**Comment by thomasmalley** [comment]
The latest 1.3.14 Update doesn't fix this retroactive. If it happened before 1.3.14 it will happen again, even with the fix.
If the Page Template is still within the active (global) StyleKit it is hard to remove it again, since the Page Template switches back to the one "contained" in the StyleKit within seconds. 
Do you have any solution for that case?

**Comment by JohnPixle** [comment]
⚠️  Re-opening this issue for further investigation.

**Comment by thomasmalley** [comment]
> 1.3.15 – November 29, 2019
> * Fix: Remove stored template values from existing SKs 

🙏🏻 Thank You :)
