### ISSUE TITLE
Update SK Settings sidebar

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#374]
This is regarding the addition of the SK PRO UPGRADE panel at the settings.

🌀 [**Here is the FIGMA file.**](https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=1231%3A8945). **Please follow the current default admin styles, not the figma ones.**

### **1. Upgrade to Pro panel**
⚠️ This must exist only when SK PRO is not installed in the site.

![Screenshot 2020-03-30 at 20 13 49](https://user-images.githubusercontent.com/4193672/77941632-2305e700-72c3-11ea-917f-b2db6a8ec17d.png)

### **2. Update the existing panel**

There are also some suggested tweaks in the existing panel, mainly for reducing the height.

![Screenshot 2020-03-30 at 20 13 58](https://user-images.githubusercontent.com/4193672/77941804-65c7bf00-72c3-11ea-9e2c-a9313ff759a1.png)

**Comment by mauryaratan** [comment]
@JohnPixle I don't like distributing the coupon code publicly like that bro.

What if we collect users' name + email address here? And send them a personalized code? This has a few benefits:

- No one scheme into publicly sharing the coupon code aka making a way around to get a discount code
- We can add them to a specific AC list **Potential Customers** when they request a coupon code
- If a user doesn't purchase or changes their mind, we'll know and do something with that.
- And since upon purchase, a user is added to the **Pro** customers list. We can run a workflow that goes: If in "Potential Customers" and didn't purchase within 48 hours, send an automated reminder.
- To make this more effective, we can remove the user from **Potential Customers** list once purchased.

Let me know your thoughts!

**Comment by JohnPixle** [comment]
@mauryaratan Ok, we can do it as you say.
[Updated the figma.](https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=1231%3A8945)

![Screenshot 2020-04-03 at 14 32 41](https://user-images.githubusercontent.com/4193672/78356333-0534cc80-75b8-11ea-952e-578731e916a5.png)
