### ISSUE TITLE
I have Warning

### ISSUE THREAD

**Issue by mahdimehri** [mauryaratan/analogwp-templates#474]
hi 
I have Warning: filemtime(): stat failed for E:\xampp\htdocs\Elementor\wp-content\plugins\analogwp-templates-develop/assets/js/app.js  
in 
and this plagin its not work for me on xampp
https://github.com/analogwp/analogwp-templates/blob/32377fd7b4a3c04161280f05aa8c69b7abd5091e/inc/class-elementor.php#L100

**Comment by mauryaratan** [comment]
Hey @mahdimehri, did you download directly from Github? If so, the assets need to be compiled.

Or you can try downloading directly from https://downloads.wordpress.org/plugin/analogwp-templates.1.8.0.zip

Let me know if the issue still persists for you. Thanks.

**Comment by lushkant** [comment]
Hey @mahdimehri, we have tested SK on windows running with a XAMPP install and everything looks good, I think you have downloaded directly from this repository, and as @mauryaratan pointed above you need to first compile the assets in order to get all of our SK plugin features working.

Please reach out to us via [AnalogWP Support](https://analogwp.com/support/)

Closing this issue as of now :)
