### ISSUE TITLE
Frozen Editor area after SK "Save as"

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#539]
When I "Save As..." a Style Kit, the editor is supposed to make a refresh, and apply the style kit to the page. Two things:

- [ ] I am not sure that the Style Kit is being applied on the page successfully. Some times it doesn't.
- [ ] After the auto-refresh in the editor, the editor is frozen, you cannot click and select elements, and you can not drop widgets.

I made a 2min loom showing the issue in action.

https://www.loom.com/share/9ae7737db010487aa4fc8249d63faa5f

**Comment by lushkant** [comment]
Hey @JohnPixle, as per lots of testing and looking into it turns out that the discard function from Elementor does throw an error but it doesn't affect the process of saving a new kit. And this happens only when you save the kit without any changes to the current kit (which is expected).

So the results were different at play only, after some looking around into play site seems like there is a bad config. Can you try the version I sent you in Slack locally and confirm if it works fine there?

**Comment by JohnPixle** [comment]
Ok, since this works fine, shall I close this issue? Or you want to manage this in another way?

**Comment by lushkant** [comment]
> Ok, since this works fine, shall I close this issue? Or you want to manage this in another way?

Yes please close it.
